version: "3.8"
services:
  db:
    image: postgres
    container_name: ad_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ad_pgdata:/var/lib/postgresql/data
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    networks:
      ad:
         # ipv4_address: 172.18.0.3
  pgadmin:
    image: dpage/pgadmin4
    container_name: ad_pgpadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - ad_pgadmin_data:/var/lib/pgadmin
    networks:
      ad:
         # ipv4_address: 172.18.0.2 
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: ad_api
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
    networks:
      ad:
         # ipv4_address: 172.18.0.4

volumes:
  ad_pgdata:
  ad_pgadmin_data:

networks:
  ad:
    driver: bridge
    # ipam:
    #  config:
    #    - subnet: 172.18.0.0/16
