CREATE TABLE IF NOT EXISTS public.departments
(
    department_id integer NOT NULL,
    department_name text COLLATE pg_catalog."default" NOT NULL,
    manager_id integer NOT NULL,
    CONSTRAINT pk_1 PRIMARY KEY (department_id)
)
TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.users
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 2147483647 CACHE 1 ),
    user_first_name text COLLATE pg_catalog."default" NOT NULL,
    user_last_name text COLLATE pg_catalog."default" NOT NULL,
    user_date_of_birth date NOT NULL,
    user_encrypted_password text COLLATE pg_catalog."default" NOT NULL,
    user_created_at timestamp with time zone NOT NULL,
    user_updated_at timestamp with time zone,
    user_last_connected timestamp with time zone,
    user_email text COLLATE pg_catalog."default" NOT NULL,
    user_phone_number text COLLATE pg_catalog."default" NOT NULL,
    user_country text COLLATE pg_catalog."default",
    CONSTRAINT pk_2 PRIMARY KEY (user_id)
)
TABLESPACE pg_default;


CREATE TABLE IF NOT EXISTS public.employees
(
    employee_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employee_first_name text COLLATE pg_catalog."default" NOT NULL,
    employee_last_name text COLLATE pg_catalog."default" NOT NULL,
    employee_email text COLLATE pg_catalog."default" NOT NULL,
    employee_date_of_birth date NOT NULL,
    department_id integer NOT NULL,
    employee_salary integer NOT NULL,
    employee_updated_at timestamp without time zone,
    employee_created_at timestamp with time zone NOT NULL,
    employee_phone_number text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_3 PRIMARY KEY (employee_id),
    CONSTRAINT fk_14_2 FOREIGN KEY (department_id)
        REFERENCES public.departments (department_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.moderation_department
(
    moderator_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    meeting_id integer,
    department_id integer NOT NULL,
    employee_id integer NOT NULL,
    CONSTRAINT pk_4 PRIMARY KEY (moderator_id),
    CONSTRAINT fk_14 FOREIGN KEY (department_id)
        REFERENCES public.departments (department_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_14_1 FOREIGN KEY (employee_id)
        REFERENCES public.employees (employee_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.human_resources_department
(
    resources_id integer NOT NULL,
    department_id integer NOT NULL,
    employee_id integer NOT NULL,
    CONSTRAINT pk_5 PRIMARY KEY (resources_id),
    CONSTRAINT fk_17 FOREIGN KEY (department_id)
        REFERENCES public.departments (department_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_18 FOREIGN KEY (employee_id)
        REFERENCES public.employees (employee_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;


CREATE TABLE IF NOT EXISTS public.posts
(
    post_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    post_title text COLLATE pg_catalog."default" NOT NULL,
    moderator_id integer NOT NULL,
    post_created_at timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    post_content text COLLATE pg_catalog."default",
    post_updated_at timestamp with time zone,
    CONSTRAINT pk_6 PRIMARY KEY (post_id),
    CONSTRAINT fk_12 FOREIGN KEY (moderator_id)
        REFERENCES public.moderation_department (moderator_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_16_2 FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.comments
(
    comment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    comment_content text COLLATE pg_catalog."default" NOT NULL,
    post_id integer NOT NULL,
    user_id integer NOT NULL,
    comment_created_at timestamp with time zone NOT NULL,
    comment_updated_at timestamp with time zone NOT NULL,
    CONSTRAINT pk_7 PRIMARY KEY (comment_id),
    CONSTRAINT fk_15 FOREIGN KEY (post_id)
        REFERENCES public.posts (post_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_16 FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT pk_8 PRIMARY KEY (customer_id),
    CONSTRAINT fk_4 FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.sales_moderation_department
(
    sales_rep_id integer NOT NULL,
    sale_id integer NOT NULL,
    manager_id integer NOT NULL,
    department_id integer NOT NULL,
    employee_id integer NOT NULL,
    CONSTRAINT pk_9 PRIMARY KEY (sales_rep_id),
    CONSTRAINT fk_13 FOREIGN KEY (department_id)
        REFERENCES public.departments (department_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_18_1 FOREIGN KEY (employee_id)
        REFERENCES public.employees (employee_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.sellers
(
    seller_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT pk_10 PRIMARY KEY (seller_id),
    CONSTRAINT fk_3 FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.marketplace
(
    sale_id integer NOT NULL,
    sale_title text COLLATE pg_catalog."default" NOT NULL,
    sale_desc text COLLATE pg_catalog."default" NOT NULL,
    sale_price double precision NOT NULL,
    customer_id integer NOT NULL,
    seller_id integer NOT NULL,
    sales_rep_id integer NOT NULL,
    CONSTRAINT pk_11 PRIMARY KEY (sale_id),
    CONSTRAINT fk_14_3 FOREIGN KEY (seller_id)
        REFERENCES public.sellers (seller_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_18_2 FOREIGN KEY (sales_rep_id)
        REFERENCES public.sales_moderation_department (sales_rep_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_6 FOREIGN KEY (customer_id)
        REFERENCES public.customers (customer_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;


CREATE TABLE IF NOT EXISTS public.meetings
(
    meeting_id integer NOT NULL,
    moderator_id integer NOT NULL,
    meeting_name text COLLATE pg_catalog."default" NOT NULL,
    meeting_date date NOT NULL,
    meeting_desc text COLLATE pg_catalog."default" NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT pk_12 PRIMARY KEY (meeting_id),
    CONSTRAINT fk_11 FOREIGN KEY (moderator_id)
        REFERENCES public.moderation_department (moderator_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_16_1 FOREIGN KEY (user_id)
        REFERENCES public.users (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
TABLESPACE pg_default;


CREATE TABLE IF NOT EXISTS public.logs
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    function_name text COLLATE pg_catalog."default" NOT NULL,
    execution_time integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT logs_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;


CREATE TABLE IF NOT EXISTS public.logs_index
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    function_name text COLLATE pg_catalog."default" NOT NULL,
    execution_time integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT logs_index_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;


CREATE TABLE IF NOT EXISTS public.logs_partition
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    function_name text COLLATE pg_catalog."default" NOT NULL,
    execution_time integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT logs_partition_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;
